Hackerank/HackerRank/HackerRank/urls.py
from django.contrib import admin
from django.urls import path,include
from quiz import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView


router=DefaultRouter()
router.register("api/v1/categories",views.CategoriesView,basename="categories")
router.register("api/v1/questions",views.QuestionsView,basename="questions")

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/token/",TokenObtainPairView.as_view()),
    path("api/v1/token/refresh/",TokenRefreshView.as_view()),
    path("web/",include("quizweb.urls"))
    # path("api/v1/token/",ObtainAuthToken.as_view()),


]+router.urls

Hackerank/HackerRank/quizweb/urls.py
from django.urls import path
from quizweb import views

urlpatterns=[
    path("register",views.SignUpView.as_view(),name="signup"),
    path("login",views.SignInView.as_view(),name="signin"),
    path("home",views.HomeView.as_view(),name="home"),
    path("quizes/home",views.QuizHomeView.as_view(),name="quiz-home"),
    path("questions/all/<str:cat>/<str:mode>/",views.QuestionListView.as_view(),name="question-list"),
    path("quiz/record/",views.QuizRecordView.as_view(),name="quiz-record"),

]

Hackerank/HackerRank/quiz/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    is_active=models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name
    
class Questions(models.Model):
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)   
    options=(
        ('easy','easy'),
        ('medium','medium'),
        ('hard','hard')
           ) 
    mode=models.CharField(max_length=200,choices=options,default='easy')
    mark=models.PositiveIntegerField(default=2)
    question=models.CharField(max_length=200)

    
    @property
    def choices(self):
        return Answers.objects.filter(question=self)
    
    @property
    def answer(self):
        return Answers.objects.get(question=self,is_correct=True)

    def __str__(self) -> str:
        return self.question
    

class Answers(models.Model):
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)
    options=models.CharField(max_length=200) 
    is_correct=models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.options 

class QuizRecord(models.Model):
    marks_obtained=models.PositiveIntegerField()  
    right_answer_count=models.PositiveIntegerField()
    wrong_answer_count=models.PositiveIntegerField()
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    date=models.DateField(auto_now_add=True)

Hackerank/HackerRank/quizweb/models.py
from django.db import models

# Create your models here.

Hackerank/HackerRank/quizweb/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


from django import forms


class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["email","username","password1","password2"]




class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

Hackerank/HackerRank/quizweb/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,CreateView,FormView,TemplateView,ListView

from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages


from django.urls import reverse_lazy

from quizweb.forms import RegistrationForm,LoginForm

from quiz.models import Category,Questions,QuizRecord


import random

class SignUpView(CreateView):
    form_class=RegistrationForm
    model=User
    template_name="register.html"
    success_url=reverse_lazy("signin")


    def form_valid(self, form):
        messages.success(self.request,"account has been created")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"failed to create account")
        return super().form_invalid(form)
    
class SignInView(FormView):
    form_class=LoginForm
    template_name="login.html"   


    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("home")
            else:
                return render(request,self.template_name,{"form":form})
            

class HomeView(TemplateView):
    template_name="home.html"           
        
class QuizHomeView(View):

    def get(self,request,*args,**kwargs):
        qs=Category.objects.all()
        return render(request,"quiz-home.html",{"cats":qs})
    
    def post(self,request,*args,**kwargs):
        cat=request.POST.get("category")
        mode=request.POST.get("mode")
        print(cat,mode)
        return redirect("question-list",cat=cat,mode=mode)
    
from django.db.models import Sum
class QuestionListView(View):  
    def get(self,request,*args,**kwargs):
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        qs=list(Questions.objects.filter(category__name=category,mode=mode))
        # grand_total=0
        # for q in qob:
        #     grand_total+=q.mark
        # print(grand_total)   
        random.shuffle(qs)       
        return render(request,"question-list.html",{"questions":qs}) 
     
    def post(self,request,*args,**kwargs):
        data=request.POST.dict()
        data.pop("csrfmiddlewaretoken")
        questions_attended=len(data)
        marks_obtained=0
        wrong_answer_count=0
        for q,ans in data.items():
            question=Questions.objects.get(question=q)
            right_answer_obj=question.answer
            if(right_answer_obj.options==ans):
                marks_obtained=marks_obtained+question.mark
            else:
                wrong_answer_count+=1 
            right_answer_count=questions_attended-wrong_answer_count       
        print(marks_obtained,questions_attended,wrong_answer_count,right_answer_count)

        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        result=''
        total=Questions.objects.filter(category__name=category,mode=mode).aggregate(Sum('mark')).get('mark__sum')     
        if total/2 <=marks_obtained:
            result='pass'
        else:
            result='failed'   

        data=QuizRecord.objects.create(marks_obtained=marks_obtained,right_answer_count=right_answer_count,wrong_answer_count=wrong_answer_count,user=request.user)        
        return render(request,"quiz-mark.html",{"marks_obtained":marks_obtained,"questions_attended":questions_attended,"result":result})


class QuizRecordView(ListView):
    model=QuizRecord
    template_name="quiz-record.html"
    context_object_name="records"

    def get_queryset(self):
        return QuizRecord.objects.filter(user=self.request.user)
    

Hackerank/HackerRank/quizweb/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <h3>Welcome {{request.user}}</h3>
    <a href="{%url 'quiz-home'%}" class="btn btn-outline-info">Start Quiz</a><br>
    <a href="{%url 'quiz-record'%}">History</a>
    
</body>
</html>

Hackerank/HackerRank/quizweb/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit">
    </form>
    
</body>
</html>

Hackerank/HackerRank/quizweb/templates/question-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <div class="container border rounded p-2 mt-4">
        <form action="" method="post">
            {%csrf_token%}
            {%for q in questions%}
        <div class="border border-bottom mb-3">
            <h4>{{q.question}} marks({{q.mark}})</h4>

            <div style="height: 80px;">
                {%for ch in q.choices%}
             <span class="p-2" > 
                <input type="radio" name="{{q}}" value="{{ch}}"> {{ch}}</span>
            
            {%endfor%}
            </div>
        </div>

        {%endfor%}
        <button type="submit">submit</button>
        </form>
    </div>

</body>
</html>

Hackerank/HackerRank/quizweb/templates/quiz-home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3">
                <form action="" method="post">
                    {%csrf_token%}

                    <label for="id_category" class="form-text">select a category</label>
                    <select name="category" id="id_category" class="form-select mb-3">
                        {%for cat in cats%}
                        <option value="{{cat.name}}">{{cat.name}}</option>
                        {%endfor%}
                        
                    </select>


                    <label for="id_mode" class="form-text">select a mode</label>
                    <select name="mode" id="id_mode" class="form-select mb-3">
                        <option value="easy">easy</option>
                        <option value="medium">medium</option>
                        <option value="hard">hard</option>

                    </select>
                    <br>

                    <input type="submit" value="let's start" class="btn btn-outline-success">
                </form>

            </div>
            <div class="col-3"></div>
        </div>
    </div>
</body>
</html>

Hackerank/HackerRank/quizweb/templates/quiz-mark.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>MARKS</h3>
    <h3>total mark obtained {{marks_obtained}}</h3>
    <h3>Questions attended {{questions_attended}}</h3>
    <h3>status {{result}}</h3>
</body>
</html>

Hackerank/HackerRank/quizweb/templates/quiz-record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        {%for record in records%}
        <div>
            welcome {{request.user}}<br>           
            marks obtained={{record.marks_obtained}}
            right answer count={{record.right_answer_count}}
            wrong answer count={{record.wrong_answer_count}}
            date={{record.date}}


        </div>
        {%endfor%}
    </div>
</body>
</html>

Hackerank/HackerRank/quizweb/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit">
        
    </form>
    
</body>
</html>